apiVersion: v1
kind: Service
metadata:
  name: lugx-prod-service
spec:
  selector:
    app: lugx-gaming-prod
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: lugxprodport
      nodePort: 30011